name: projectbotany
services:
  # -----------------------------------------------------------
  #  ğŸŒ¿ ProjectBotany (Production / Base)
  # -----------------------------------------------------------
  projectbotany-vite:
    build:
      context: ./vite
      dockerfile: Dockerfile
      target: prod # æœ¬ç•ªç”¨ã‚¹ãƒ†ãƒ¼ã‚¸ã‚’ä½¿ç”¨
    container_name: projectbotany-vite
    restart: unless-stopped
    # æœ¬ç•ªã§ã¯ãƒœãƒªãƒ¥ãƒ¼ãƒ ãƒã‚¦ãƒ³ãƒˆã‚’è¡Œã‚ãªã„ (COPYæ¸ˆã¿ã®ãŸã‚)
    labels:
      caddy: http://projectbotany.app.fukaya-sus.lab
      caddy.reverse_proxy: "{{upstreams 80}}" # Nginxã®80ç•ªãƒãƒ¼ãƒˆã¸

networks:
  fukaya-lab-network:
    external: true
    name: fukaya-lab-network